

const ChoosePokemonForm = () => {

  const data = (
    <>
      <div id="container-ChoosePokemonForm">
        <input type="text" onKeyUp={(e) => searchMons(e)} id="myInput" placeholder="Search for Pokemon..." />

        <ul id="myUL">
          <li><a href="/">Bulbasaur</a></li>
          <li><a href="/">Ivysaur</a></li>
          <li><a href="/">Venusaur</a></li>
          <li><a href="/">Charmander</a></li>
          <li><a href="/">Charmeleon</a></li>
          <li><a href="/">Charizard</a></li>
          <li><a href="/">Squirtle</a></li>
          <li><a href="/">Wartortle</a></li>
          <li><a href="/">Blastoise</a></li>
          <li style={{ display: "none" }}><a href="/">Caterpie</a></li>
          <li style={{ display: "none" }}><a href="/">Metapod</a></li>
          <li style={{ display: "none" }}><a href="/">Butterfree</a></li>
          <li style={{ display: "none" }}><a href="/">Weedle</a></li>
          <li style={{ display: "none" }}><a href="/">Kakuna</a></li>
          <li style={{ display: "none" }}><a href="/">Beedrill</a></li>
          <li style={{ display: "none" }}><a href="/">Pidgey</a></li>
          <li style={{ display: "none" }}><a href="/">Pidgeotto</a></li>
          <li style={{ display: "none" }}><a href="/">Pidgeot</a></li>
          <li style={{ display: "none" }}><a href="/">Rattata</a></li>
          <li style={{ display: "none" }}><a href="/">Raticate</a></li>
          <li style={{ display: "none" }}><a href="/">Spearow</a></li>
          <li style={{ display: "none" }}><a href="/">Fearow</a></li>
          <li style={{ display: "none" }}><a href="/">Ekans</a></li>
          <li style={{ display: "none" }}><a href="/">Arbok</a></li>
          <li style={{ display: "none" }}><a href="/">Pikachu</a></li>
          <li style={{ display: "none" }}><a href="/">Raichu</a></li>
          <li style={{ display: "none" }}><a href="/">Sandshrew</a></li>
          <li style={{ display: "none" }}><a href="/">Sandslash</a></li>
          <li style={{ display: "none" }}><a href="/">Nidoran♀</a></li>
          <li style={{ display: "none" }}><a href="/">Nidorina</a></li>
          <li style={{ display: "none" }}><a href="/">Nidoqueen</a></li>
          <li style={{ display: "none" }}><a href="/">Nidoran♂</a></li>
          <li style={{ display: "none" }}><a href="/">Nidorino</a></li>
          <li style={{ display: "none" }}><a href="/">Nidoking</a></li>
          <li style={{ display: "none" }}><a href="/">Clefairy</a></li>
          <li style={{ display: "none" }}><a href="/">Clefable</a></li>
          <li style={{ display: "none" }}><a href="/">Vulpix</a></li>
          <li style={{ display: "none" }}><a href="/">Ninetales</a></li>
          <li style={{ display: "none" }}><a href="/">Jigglypuff</a></li>
          <li style={{ display: "none" }}><a href="/">Wigglytuff</a></li>
          <li style={{ display: "none" }}><a href="/">Zubat</a></li>
          <li style={{ display: "none" }}><a href="/">Golbat</a></li>
          <li style={{ display: "none" }}><a href="/">Oddish</a></li>
          <li style={{ display: "none" }}><a href="/">Gloom</a></li>
          <li style={{ display: "none" }}><a href="/">Vileplume</a></li>
          <li style={{ display: "none" }}><a href="/">Paras</a></li>
          <li style={{ display: "none" }}><a href="/">Parasect</a></li>
          <li style={{ display: "none" }}><a href="/">Venonat</a></li>
          <li style={{ display: "none" }}><a href="/">Venomoth</a></li>
          <li style={{ display: "none" }}><a href="/">Diglett</a></li>
          <li style={{ display: "none" }}><a href="/">Dugtrio</a></li>
          <li style={{ display: "none" }}><a href="/">Meowth</a></li>
          <li style={{ display: "none" }}><a href="/">Persian</a></li>
          <li style={{ display: "none" }}><a href="/">Psyduck</a></li>
          <li style={{ display: "none" }}><a href="/">Golduck</a></li>
          <li style={{ display: "none" }}><a href="/">Mankey</a></li>
          <li style={{ display: "none" }}><a href="/">Primeape</a></li>
          <li style={{ display: "none" }}><a href="/">Growlithe</a></li>
          <li style={{ display: "none" }}><a href="/">Arcanine</a></li>
          <li style={{ display: "none" }}><a href="/">Poliwag</a></li>
          <li style={{ display: "none" }}><a href="/">Poliwhirl</a></li>
          <li style={{ display: "none" }}><a href="/">Poliwrath</a></li>
          <li style={{ display: "none" }}><a href="/">Abra</a></li>
          <li style={{ display: "none" }}><a href="/">Kadabra</a></li>
          <li style={{ display: "none" }}><a href="/">Alakazam</a></li>
          <li style={{ display: "none" }}><a href="/">Machop</a></li>
          <li style={{ display: "none" }}><a href="/">Machoke</a></li>
          <li style={{ display: "none" }}><a href="/">Machamp</a></li>
          <li style={{ display: "none" }}><a href="/">Bellsprout</a></li>
          <li style={{ display: "none" }}><a href="/">Weepinbell</a></li>
          <li style={{ display: "none" }}><a href="/">Victreebel</a></li>
          <li style={{ display: "none" }}><a href="/">Tentacool</a></li>
          <li style={{ display: "none" }}><a href="/">Tentacruel</a></li>
          <li style={{ display: "none" }}><a href="/">Geodude</a></li>
          <li style={{ display: "none" }}><a href="/">Graveler</a></li>
          <li style={{ display: "none" }}><a href="/">Golem</a></li>
          <li style={{ display: "none" }}><a href="/">Ponyta</a></li>
          <li style={{ display: "none" }}><a href="/">Rapidash</a></li>
          <li style={{ display: "none" }}><a href="/">Slowpoke</a></li>
          <li style={{ display: "none" }}><a href="/">Slowbro</a></li>
          <li style={{ display: "none" }}><a href="/">Magnemite</a></li>
          <li style={{ display: "none" }}><a href="/">Magneton</a></li>
          <li style={{ display: "none" }}><a href="/">Farfetch'd</a></li>
          <li style={{ display: "none" }}><a href="/">Doduo</a></li>
          <li style={{ display: "none" }}><a href="/">Dodrio</a></li>
          <li style={{ display: "none" }}><a href="/">Seel</a></li>
          <li style={{ display: "none" }}><a href="/">Dewgong</a></li>
          <li style={{ display: "none" }}><a href="/">Grimer</a></li>
          <li style={{ display: "none" }}><a href="/">Muk</a></li>
          <li style={{ display: "none" }}><a href="/">Shellder</a></li>
          <li style={{ display: "none" }}><a href="/">Cloyster</a></li>
          <li style={{ display: "none" }}><a href="/">Gastly</a></li>
          <li style={{ display: "none" }}><a href="/">Haunter</a></li>
          <li style={{ display: "none" }}><a href="/">Gengar</a></li>
          <li style={{ display: "none" }}><a href="/">Onix</a></li>
          <li style={{ display: "none" }}><a href="/">Drowzee</a></li>
          <li style={{ display: "none" }}><a href="/">Hypno</a></li>
          <li style={{ display: "none" }}><a href="/">Krabby</a></li>
          <li style={{ display: "none" }}><a href="/">Kingler</a></li>
          <li style={{ display: "none" }}><a href="/">Voltorb</a></li>
          <li style={{ display: "none" }}><a href="/">Electrode</a></li>
          <li style={{ display: "none" }}><a href="/">Exeggcute</a></li>
          <li style={{ display: "none" }}><a href="/">Exeggutor</a></li>
          <li style={{ display: "none" }}><a href="/">Cubone</a></li>
          <li style={{ display: "none" }}><a href="/">Marowak</a></li>
          <li style={{ display: "none" }}><a href="/">Hitmonlee</a></li>
          <li style={{ display: "none" }}><a href="/">Hitmonchan</a></li>
          <li style={{ display: "none" }}><a href="/">Lickitung</a></li>
          <li style={{ display: "none" }}><a href="/">Koffing</a></li>
          <li style={{ display: "none" }}><a href="/">Weezing</a></li>
          <li style={{ display: "none" }}><a href="/">Rhyhorn</a></li>
          <li style={{ display: "none" }}><a href="/">Rhydon</a></li>
          <li style={{ display: "none" }}><a href="/">Chansey</a></li>
          <li style={{ display: "none" }}><a href="/">Tangela</a></li>
          <li style={{ display: "none" }}><a href="/">Kangaskhan</a></li>
          <li style={{ display: "none" }}><a href="/">Horsea</a></li>
          <li style={{ display: "none" }}><a href="/">Seadra</a></li>
          <li style={{ display: "none" }}><a href="/">Goldeen</a></li>
          <li style={{ display: "none" }}><a href="/">Seaking</a></li>
          <li style={{ display: "none" }}><a href="/">Staryu</a></li>
          <li style={{ display: "none" }}><a href="/">Starmie</a></li>
          <li style={{ display: "none" }}><a href="/">Mr. Mime</a></li>
          <li style={{ display: "none" }}><a href="/">Scyther</a></li>
          <li style={{ display: "none" }}><a href="/">Jynx</a></li>
          <li style={{ display: "none" }}><a href="/">Electabuzz</a></li>
          <li style={{ display: "none" }}><a href="/">Magmar</a></li>
          <li style={{ display: "none" }}><a href="/">Pinsir</a></li>
          <li style={{ display: "none" }}><a href="/">Tauros</a></li>
          <li style={{ display: "none" }}><a href="/">Magikarp</a></li>
          <li style={{ display: "none" }}><a href="/">Gyarados</a></li>
          <li style={{ display: "none" }}><a href="/">Lapras</a></li>
          <li style={{ display: "none" }}><a href="/">Ditto</a></li>
          <li style={{ display: "none" }}><a href="/">Eevee</a></li>
          <li style={{ display: "none" }}><a href="/">Vaporeon</a></li>
          <li style={{ display: "none" }}><a href="/">Jolteon</a></li>
          <li style={{ display: "none" }}><a href="/">Flareon</a></li>
          <li style={{ display: "none" }}><a href="/">Porygon</a></li>
          <li style={{ display: "none" }}><a href="/">Omanyte</a></li>
          <li style={{ display: "none" }}><a href="/">Omastar</a></li>
          <li style={{ display: "none" }}><a href="/">Kabuto</a></li>
          <li style={{ display: "none" }}><a href="/">Kabutops</a></li>
          <li style={{ display: "none" }}><a href="/">Aerodactyl</a></li>
          <li style={{ display: "none" }}><a href="/">Snorlax</a></li>
          <li style={{ display: "none" }}><a href="/">Articuno</a></li>
          <li style={{ display: "none" }}><a href="/">Zapdos</a></li>
          <li style={{ display: "none" }}><a href="/">Moltres</a></li>
          <li style={{ display: "none" }}><a href="/">Dratini</a></li>
          <li style={{ display: "none" }}><a href="/">Dragonair</a></li>
          <li style={{ display: "none" }}><a href="/">Dragonite</a></li>
          <li style={{ display: "none" }}><a href="/">Mewtwo</a></li>
          <li style={{ display: "none" }}><a href="/">Mew</a></li>
          <li style={{ display: "none" }}><a href="/">Chikorita</a></li>
          <li style={{ display: "none" }}><a href="/">Bayleef</a></li>
          <li style={{ display: "none" }}><a href="/">Meganium</a></li>
          <li style={{ display: "none" }}><a href="/">Cyndaquil</a></li>
          <li style={{ display: "none" }}><a href="/">Quilava</a></li>
          <li style={{ display: "none" }}><a href="/">Typhlosion</a></li>
          <li style={{ display: "none" }}><a href="/">Totodile</a></li>
          <li style={{ display: "none" }}><a href="/">Croconaw</a></li>
          <li style={{ display: "none" }}><a href="/">Feraligatr</a></li>
          <li style={{ display: "none" }}><a href="/">Sentret</a></li>
          <li style={{ display: "none" }}><a href="/">Furret</a></li>
          <li style={{ display: "none" }}><a href="/">Hoothoot</a></li>
          <li style={{ display: "none" }}><a href="/">Noctowl</a></li>
          <li style={{ display: "none" }}><a href="/">Ledyba</a></li>
          <li style={{ display: "none" }}><a href="/">Ledian</a></li>
          <li style={{ display: "none" }}><a href="/">Spinarak</a></li>
          <li style={{ display: "none" }}><a href="/">Ariados</a></li>
          <li style={{ display: "none" }}><a href="/">Crobat</a></li>
          <li style={{ display: "none" }}><a href="/">Chinchou</a></li>
          <li style={{ display: "none" }}><a href="/">Lanturn</a></li>
          <li style={{ display: "none" }}><a href="/">Pichu</a></li>
          <li style={{ display: "none" }}><a href="/">Cleffa</a></li>
          <li style={{ display: "none" }}><a href="/">Igglybuff</a></li>
          <li style={{ display: "none" }}><a href="/">Togepi</a></li>
          <li style={{ display: "none" }}><a href="/">Togetic</a></li>
          <li style={{ display: "none" }}><a href="/">Natu</a></li>
          <li style={{ display: "none" }}><a href="/">Xatu</a></li>
          <li style={{ display: "none" }}><a href="/">Mareep</a></li>
          <li style={{ display: "none" }}><a href="/">Flaaffy</a></li>
          <li style={{ display: "none" }}><a href="/">Ampharos</a></li>
          <li style={{ display: "none" }}><a href="/">Bellossom</a></li>
          <li style={{ display: "none" }}><a href="/">Marill</a></li>
          <li style={{ display: "none" }}><a href="/">Azumarill</a></li>
          <li style={{ display: "none" }}><a href="/">Sudowoodo</a></li>
          <li style={{ display: "none" }}><a href="/">Politoed</a></li>
          <li style={{ display: "none" }}><a href="/">Hoppip</a></li>
          <li style={{ display: "none" }}><a href="/">Skiploom</a></li>
          <li style={{ display: "none" }}><a href="/">Jumpluff</a></li>
          <li style={{ display: "none" }}><a href="/">Aipom</a></li>
          <li style={{ display: "none" }}><a href="/">Sunkern</a></li>
          <li style={{ display: "none" }}><a href="/">Sunflora</a></li>
          <li style={{ display: "none" }}><a href="/">Yanma</a></li>
          <li style={{ display: "none" }}><a href="/">Wooper</a></li>
          <li style={{ display: "none" }}><a href="/">Quagsire</a></li>
          <li style={{ display: "none" }}><a href="/">Espeon</a></li>
          <li style={{ display: "none" }}><a href="/">Umbreon</a></li>
          <li style={{ display: "none" }}><a href="/">Murkrow</a></li>
          <li style={{ display: "none" }}><a href="/">Slowking</a></li>
          <li style={{ display: "none" }}><a href="/">Misdreavus</a></li>
          <li style={{ display: "none" }}><a href="/">Unown</a></li>
          <li style={{ display: "none" }}><a href="/">Wobbuffet</a></li>
          <li style={{ display: "none" }}><a href="/">Girafarig</a></li>
          <li style={{ display: "none" }}><a href="/">Pineco</a></li>
          <li style={{ display: "none" }}><a href="/">Forretress</a></li>
          <li style={{ display: "none" }}><a href="/">Dunsparce</a></li>
          <li style={{ display: "none" }}><a href="/">Gligar</a></li>
          <li style={{ display: "none" }}><a href="/">Steelix</a></li>
          <li style={{ display: "none" }}><a href="/">Snubbull</a></li>
          <li style={{ display: "none" }}><a href="/">Granbull</a></li>
          <li style={{ display: "none" }}><a href="/">Qwilfish</a></li>
          <li style={{ display: "none" }}><a href="/">Scizor</a></li>
          <li style={{ display: "none" }}><a href="/">Shuckle</a></li>
          <li style={{ display: "none" }}><a href="/">Heracross</a></li>
          <li style={{ display: "none" }}><a href="/">Sneasel</a></li>
          <li style={{ display: "none" }}><a href="/">Teddiursa</a></li>
          <li style={{ display: "none" }}><a href="/">Ursaring</a></li>
          <li style={{ display: "none" }}><a href="/">Slugma</a></li>
          <li style={{ display: "none" }}><a href="/">Magcargo</a></li>
          <li style={{ display: "none" }}><a href="/">Swinub</a></li>
          <li style={{ display: "none" }}><a href="/">Piloswine</a></li>
          <li style={{ display: "none" }}><a href="/">Corsola</a></li>
          <li style={{ display: "none" }}><a href="/">Remoraid</a></li>
          <li style={{ display: "none" }}><a href="/">Octillery</a></li>
          <li style={{ display: "none" }}><a href="/">Delibird</a></li>
          <li style={{ display: "none" }}><a href="/">Mantine</a></li>
          <li style={{ display: "none" }}><a href="/">Skarmory</a></li>
          <li style={{ display: "none" }}><a href="/">Houndour</a></li>
          <li style={{ display: "none" }}><a href="/">Houndoom</a></li>
          <li style={{ display: "none" }}><a href="/">Kingdra</a></li>
          <li style={{ display: "none" }}><a href="/">Phanpy</a></li>
          <li style={{ display: "none" }}><a href="/">Donphan</a></li>
          <li style={{ display: "none" }}><a href="/">Porygon2</a></li>
          <li style={{ display: "none" }}><a href="/">Stantler</a></li>
          <li style={{ display: "none" }}><a href="/">Smeargle</a></li>
          <li style={{ display: "none" }}><a href="/">Tyrogue</a></li>
          <li style={{ display: "none" }}><a href="/">Hitmontop</a></li>
          <li style={{ display: "none" }}><a href="/">Smoochum</a></li>
          <li style={{ display: "none" }}><a href="/">Elekid</a></li>
          <li style={{ display: "none" }}><a href="/">Magby</a></li>
          <li style={{ display: "none" }}><a href="/">Miltank</a></li>
          <li style={{ display: "none" }}><a href="/">Blissey</a></li>
          <li style={{ display: "none" }}><a href="/">Raikou</a></li>
          <li style={{ display: "none" }}><a href="/">Entei</a></li>
          <li style={{ display: "none" }}><a href="/">Suicune</a></li>
          <li style={{ display: "none" }}><a href="/">Larvitar</a></li>
          <li style={{ display: "none" }}><a href="/">Pupitar</a></li>
          <li style={{ display: "none" }}><a href="/">Tyranitar</a></li>
          <li style={{ display: "none" }}><a href="/">Lugia</a></li>
          <li style={{ display: "none" }}><a href="/">Ho-Oh</a></li>
          <li style={{ display: "none" }}><a href="/">Celebi</a></li>
          <li style={{ display: "none" }}><a href="/">Treecko</a></li>
          <li style={{ display: "none" }}><a href="/">Grovyle</a></li>
          <li style={{ display: "none" }}><a href="/">Sceptile</a></li>
          <li style={{ display: "none" }}><a href="/">Torchic</a></li>
          <li style={{ display: "none" }}><a href="/">Combusken</a></li>
          <li style={{ display: "none" }}><a href="/">Blaziken</a></li>
          <li style={{ display: "none" }}><a href="/">Mudkip</a></li>
          <li style={{ display: "none" }}><a href="/">Marshtomp</a></li>
          <li style={{ display: "none" }}><a href="/">Swampert</a></li>
          <li style={{ display: "none" }}><a href="/">Poochyena</a></li>
          <li style={{ display: "none" }}><a href="/">Mightyena</a></li>
          <li style={{ display: "none" }}><a href="/">Zigzagoon</a></li>
          <li style={{ display: "none" }}><a href="/">Linoone</a></li>
          <li style={{ display: "none" }}><a href="/">Wurmple</a></li>
          <li style={{ display: "none" }}><a href="/">Silcoon</a></li>
          <li style={{ display: "none" }}><a href="/">Beautifly</a></li>
          <li style={{ display: "none" }}><a href="/">Cascoon</a></li>
          <li style={{ display: "none" }}><a href="/">Dustox</a></li>
          <li style={{ display: "none" }}><a href="/">Lotad</a></li>
          <li style={{ display: "none" }}><a href="/">Lombre</a></li>
          <li style={{ display: "none" }}><a href="/">Ludicolo</a></li>
          <li style={{ display: "none" }}><a href="/">Seedot</a></li>
          <li style={{ display: "none" }}><a href="/">Nuzleaf</a></li>
          <li style={{ display: "none" }}><a href="/">Shiftry</a></li>
          <li style={{ display: "none" }}><a href="/">Taillow</a></li>
          <li style={{ display: "none" }}><a href="/">Swellow</a></li>
          <li style={{ display: "none" }}><a href="/">Wingull</a></li>
          <li style={{ display: "none" }}><a href="/">Pelipper</a></li>
          <li style={{ display: "none" }}><a href="/">Ralts</a></li>
          <li style={{ display: "none" }}><a href="/">Kirlia</a></li>
          <li style={{ display: "none" }}><a href="/">Gardevoir</a></li>
          <li style={{ display: "none" }}><a href="/">Surskit</a></li>
          <li style={{ display: "none" }}><a href="/">Masquerain</a></li>
          <li style={{ display: "none" }}><a href="/">Shroomish</a></li>
          <li style={{ display: "none" }}><a href="/">Breloom</a></li>
          <li style={{ display: "none" }}><a href="/">Slakoth</a></li>
          <li style={{ display: "none" }}><a href="/">Vigoroth</a></li>
          <li style={{ display: "none" }}><a href="/">Slaking</a></li>
          <li style={{ display: "none" }}><a href="/">Nincada</a></li>
          <li style={{ display: "none" }}><a href="/">Ninjask</a></li>
          <li style={{ display: "none" }}><a href="/">Shedinja</a></li>
          <li style={{ display: "none" }}><a href="/">Whismur</a></li>
          <li style={{ display: "none" }}><a href="/">Loudred</a></li>
          <li style={{ display: "none" }}><a href="/">Exploud</a></li>
          <li style={{ display: "none" }}><a href="/">Makuhita</a></li>
          <li style={{ display: "none" }}><a href="/">Hariyama</a></li>
          <li style={{ display: "none" }}><a href="/">Azurill</a></li>
          <li style={{ display: "none" }}><a href="/">Nosepass</a></li>
          <li style={{ display: "none" }}><a href="/">Skitty</a></li>
          <li style={{ display: "none" }}><a href="/">Delcatty</a></li>
          <li style={{ display: "none" }}><a href="/">Sableye</a></li>
          <li style={{ display: "none" }}><a href="/">Mawile</a></li>
          <li style={{ display: "none" }}><a href="/">Aron</a></li>
          <li style={{ display: "none" }}><a href="/">Lairon</a></li>
          <li style={{ display: "none" }}><a href="/">Aggron</a></li>
          <li style={{ display: "none" }}><a href="/">Meditite</a></li>
          <li style={{ display: "none" }}><a href="/">Medicham</a></li>
          <li style={{ display: "none" }}><a href="/">Electrike</a></li>
          <li style={{ display: "none" }}><a href="/">Manectric</a></li>
          <li style={{ display: "none" }}><a href="/">Plusle</a></li>
          <li style={{ display: "none" }}><a href="/">Minun</a></li>
          <li style={{ display: "none" }}><a href="/">Volbeat</a></li>
          <li style={{ display: "none" }}><a href="/">Illumise</a></li>
          <li style={{ display: "none" }}><a href="/">Roselia</a></li>
          <li style={{ display: "none" }}><a href="/">Gulpin</a></li>
          <li style={{ display: "none" }}><a href="/">Swalot</a></li>
          <li style={{ display: "none" }}><a href="/">Carvanha</a></li>
          <li style={{ display: "none" }}><a href="/">Sharpedo</a></li>
          <li style={{ display: "none" }}><a href="/">Wailmer</a></li>
          <li style={{ display: "none" }}><a href="/">Wailord</a></li>
          <li style={{ display: "none" }}><a href="/">Numel</a></li>
          <li style={{ display: "none" }}><a href="/">Camerupt</a></li>
          <li style={{ display: "none" }}><a href="/">Torkoal</a></li>
          <li style={{ display: "none" }}><a href="/">Spoink</a></li>
          <li style={{ display: "none" }}><a href="/">Grumpig</a></li>
          <li style={{ display: "none" }}><a href="/">Spinda</a></li>
          <li style={{ display: "none" }}><a href="/">Trapinch</a></li>
          <li style={{ display: "none" }}><a href="/">Vibrava</a></li>
          <li style={{ display: "none" }}><a href="/">Flygon</a></li>
          <li style={{ display: "none" }}><a href="/">Cacnea</a></li>
          <li style={{ display: "none" }}><a href="/">Cacturne</a></li>
          <li style={{ display: "none" }}><a href="/">Swablu</a></li>
          <li style={{ display: "none" }}><a href="/">Altaria</a></li>
          <li style={{ display: "none" }}><a href="/">Zangoose</a></li>
          <li style={{ display: "none" }}><a href="/">Seviper</a></li>
          <li style={{ display: "none" }}><a href="/">Lunatone</a></li>
          <li style={{ display: "none" }}><a href="/">Solrock</a></li>
          <li style={{ display: "none" }}><a href="/">Barboach</a></li>
          <li style={{ display: "none" }}><a href="/">Whiscash</a></li>
          <li style={{ display: "none" }}><a href="/">Corphish</a></li>
          <li style={{ display: "none" }}><a href="/">Crawdaunt</a></li>
          <li style={{ display: "none" }}><a href="/">Baltoy</a></li>
          <li style={{ display: "none" }}><a href="/">Claydol</a></li>
          <li style={{ display: "none" }}><a href="/">Lileep</a></li>
          <li style={{ display: "none" }}><a href="/">Cradily</a></li>
          <li style={{ display: "none" }}><a href="/">Anorith</a></li>
          <li style={{ display: "none" }}><a href="/">Armaldo</a></li>
          <li style={{ display: "none" }}><a href="/">Feebas</a></li>
          <li style={{ display: "none" }}><a href="/">Milotic</a></li>
          <li style={{ display: "none" }}><a href="/">Castform</a></li>
          <li style={{ display: "none" }}><a href="/">Kecleon</a></li>
          <li style={{ display: "none" }}><a href="/">Shuppet</a></li>
          <li style={{ display: "none" }}><a href="/">Banette</a></li>
          <li style={{ display: "none" }}><a href="/">Duskull</a></li>
          <li style={{ display: "none" }}><a href="/">Dusclops</a></li>
          <li style={{ display: "none" }}><a href="/">Tropius</a></li>
          <li style={{ display: "none" }}><a href="/">Chimecho</a></li>
          <li style={{ display: "none" }}><a href="/">Absol</a></li>
          <li style={{ display: "none" }}><a href="/">Wynaut</a></li>
          <li style={{ display: "none" }}><a href="/">Snorunt</a></li>
          <li style={{ display: "none" }}><a href="/">Glalie</a></li>
          <li style={{ display: "none" }}><a href="/">Spheal</a></li>
          <li style={{ display: "none" }}><a href="/">Sealeo</a></li>
          <li style={{ display: "none" }}><a href="/">Walrein</a></li>
          <li style={{ display: "none" }}><a href="/">Clamperl</a></li>
          <li style={{ display: "none" }}><a href="/">Huntail</a></li>
          <li style={{ display: "none" }}><a href="/">Gorebyss</a></li>
          <li style={{ display: "none" }}><a href="/">Relicanth</a></li>
          <li style={{ display: "none" }}><a href="/">Luvdisc</a></li>
          <li style={{ display: "none" }}><a href="/">Bagon</a></li>
          <li style={{ display: "none" }}><a href="/">Shelgon</a></li>
          <li style={{ display: "none" }}><a href="/">Salamence</a></li>
          <li style={{ display: "none" }}><a href="/">Beldum</a></li>
          <li style={{ display: "none" }}><a href="/">Metang</a></li>
          <li style={{ display: "none" }}><a href="/">Metagross</a></li>
          <li style={{ display: "none" }}><a href="/">Regirock</a></li>
          <li style={{ display: "none" }}><a href="/">Regice</a></li>
          <li style={{ display: "none" }}><a href="/">Registeel</a></li>
          <li style={{ display: "none" }}><a href="/">Latias</a></li>
          <li style={{ display: "none" }}><a href="/">Latios</a></li>
          <li style={{ display: "none" }}><a href="/">Kyogre</a></li>
          <li style={{ display: "none" }}><a href="/">Groudon</a></li>
          <li style={{ display: "none" }}><a href="/">Rayquaza</a></li>
          <li style={{ display: "none" }}><a href="/">Jirachi</a></li>
          <li style={{ display: "none" }}><a href="/">Deoxys</a></li>
          <li style={{ display: "none" }}><a href="/">Turtwig</a></li>
          <li style={{ display: "none" }}><a href="/">Grotle</a></li>
          <li style={{ display: "none" }}><a href="/">Torterra</a></li>
          <li style={{ display: "none" }}><a href="/">Chimchar</a></li>
          <li style={{ display: "none" }}><a href="/">Monferno</a></li>
          <li style={{ display: "none" }}><a href="/">Infernape</a></li>
          <li style={{ display: "none" }}><a href="/">Piplup</a></li>
          <li style={{ display: "none" }}><a href="/">Prinplup</a></li>
          <li style={{ display: "none" }}><a href="/">Empoleon</a></li>
          <li style={{ display: "none" }}><a href="/">Starly</a></li>
          <li style={{ display: "none" }}><a href="/">Staravia</a></li>
          <li style={{ display: "none" }}><a href="/">Staraptor</a></li>
          <li style={{ display: "none" }}><a href="/">Bidoof</a></li>
          <li style={{ display: "none" }}><a href="/">Bibarel</a></li>
          <li style={{ display: "none" }}><a href="/">Kricketot</a></li>
          <li style={{ display: "none" }}><a href="/">Kricketune</a></li>
          <li style={{ display: "none" }}><a href="/">Shinx</a></li>
          <li style={{ display: "none" }}><a href="/">Luxio</a></li>
          <li style={{ display: "none" }}><a href="/">Luxray</a></li>
          <li style={{ display: "none" }}><a href="/">Budew</a></li>
          <li style={{ display: "none" }}><a href="/">Roserade</a></li>
          <li style={{ display: "none" }}><a href="/">Cranidos</a></li>
          <li style={{ display: "none" }}><a href="/">Rampardos</a></li>
          <li style={{ display: "none" }}><a href="/">Shieldon</a></li>
          <li style={{ display: "none" }}><a href="/">Bastiodon</a></li>
          <li style={{ display: "none" }}><a href="/">Burmy</a></li>
          <li style={{ display: "none" }}><a href="/">Wormadam</a></li>
          <li style={{ display: "none" }}><a href="/">Mothim</a></li>
          <li style={{ display: "none" }}><a href="/">Combee</a></li>
          <li style={{ display: "none" }}><a href="/">Vespiquen</a></li>
          <li style={{ display: "none" }}><a href="/">Pachirisu</a></li>
          <li style={{ display: "none" }}><a href="/">Buizel</a></li>
          <li style={{ display: "none" }}><a href="/">Floatzel</a></li>
          <li style={{ display: "none" }}><a href="/">Cherubi</a></li>
          <li style={{ display: "none" }}><a href="/">Cherrim</a></li>
          <li style={{ display: "none" }}><a href="/">Shellos</a></li>
          <li style={{ display: "none" }}><a href="/">Gastrodon</a></li>
          <li style={{ display: "none" }}><a href="/">Ambipom</a></li>
          <li style={{ display: "none" }}><a href="/">Drifloon</a></li>
          <li style={{ display: "none" }}><a href="/">Drifblim</a></li>
          <li style={{ display: "none" }}><a href="/">Buneary</a></li>
          <li style={{ display: "none" }}><a href="/">Lopunny</a></li>
          <li style={{ display: "none" }}><a href="/">Mismagius</a></li>
          <li style={{ display: "none" }}><a href="/">Honchkrow</a></li>
          <li style={{ display: "none" }}><a href="/">Glameow</a></li>
          <li style={{ display: "none" }}><a href="/">Purugly</a></li>
          <li style={{ display: "none" }}><a href="/">Chingling</a></li>
          <li style={{ display: "none" }}><a href="/">Stunky</a></li>
          <li style={{ display: "none" }}><a href="/">Skuntank</a></li>
          <li style={{ display: "none" }}><a href="/">Bronzor</a></li>
          <li style={{ display: "none" }}><a href="/">Bronzong</a></li>
          <li style={{ display: "none" }}><a href="/">Bonsly</a></li>
          <li style={{ display: "none" }}><a href="/">Mime Jr.</a></li>
          <li style={{ display: "none" }}><a href="/">Happiny</a></li>
          <li style={{ display: "none" }}><a href="/">Chatot</a></li>
          <li style={{ display: "none" }}><a href="/">Spiritomb</a></li>
          <li style={{ display: "none" }}><a href="/">Gible</a></li>
          <li style={{ display: "none" }}><a href="/">Gabite</a></li>
          <li style={{ display: "none" }}><a href="/">Garchomp</a></li>
          <li style={{ display: "none" }}><a href="/">Munchlax</a></li>
          <li style={{ display: "none" }}><a href="/">Riolu</a></li>
          <li style={{ display: "none" }}><a href="/">Lucario</a></li>
          <li style={{ display: "none" }}><a href="/">Hippopotas</a></li>
          <li style={{ display: "none" }}><a href="/">Hippowdon</a></li>
          <li style={{ display: "none" }}><a href="/">Skorupi</a></li>
          <li style={{ display: "none" }}><a href="/">Drapion</a></li>
          <li style={{ display: "none" }}><a href="/">Croagunk</a></li>
          <li style={{ display: "none" }}><a href="/">Toxicroak</a></li>
          <li style={{ display: "none" }}><a href="/">Carnivine</a></li>
          <li style={{ display: "none" }}><a href="/">Finneon</a></li>
          <li style={{ display: "none" }}><a href="/">Lumineon</a></li>
          <li style={{ display: "none" }}><a href="/">Mantyke</a></li>
          <li style={{ display: "none" }}><a href="/">Snover</a></li>
          <li style={{ display: "none" }}><a href="/">Abomasnow</a></li>
          <li style={{ display: "none" }}><a href="/">Weavile</a></li>
          <li style={{ display: "none" }}><a href="/">Magnezone</a></li>
          <li style={{ display: "none" }}><a href="/">Lickilicky</a></li>
          <li style={{ display: "none" }}><a href="/">Rhyperior</a></li>
          <li style={{ display: "none" }}><a href="/">Tangrowth</a></li>
          <li style={{ display: "none" }}><a href="/">Electivire</a></li>
          <li style={{ display: "none" }}><a href="/">Magmortar</a></li>
          <li style={{ display: "none" }}><a href="/">Togekiss</a></li>
          <li style={{ display: "none" }}><a href="/">Yanmega</a></li>
          <li style={{ display: "none" }}><a href="/">Leafeon</a></li>
          <li style={{ display: "none" }}><a href="/">Glaceon</a></li>
          <li style={{ display: "none" }}><a href="/">Gliscor</a></li>
          <li style={{ display: "none" }}><a href="/">Mamoswine</a></li>
          <li style={{ display: "none" }}><a href="/">Porygon-Z</a></li>
          <li style={{ display: "none" }}><a href="/">Gallade</a></li>
          <li style={{ display: "none" }}><a href="/">Probopass</a></li>
          <li style={{ display: "none" }}><a href="/">Dusknoir</a></li>
          <li style={{ display: "none" }}><a href="/">Froslass</a></li>
          <li style={{ display: "none" }}><a href="/">Rotom</a></li>
          <li style={{ display: "none" }}><a href="/">Uxie</a></li>
          <li style={{ display: "none" }}><a href="/">Mesprit</a></li>
          <li style={{ display: "none" }}><a href="/">Azelf</a></li>
          <li style={{ display: "none" }}><a href="/">Dialga</a></li>
          <li style={{ display: "none" }}><a href="/">Palkia</a></li>
          <li style={{ display: "none" }}><a href="/">Heatran</a></li>
          <li style={{ display: "none" }}><a href="/">Regigigas</a></li>
          <li style={{ display: "none" }}><a href="/">Giratina</a></li>
          <li style={{ display: "none" }}><a href="/">Cresselia</a></li>
          <li style={{ display: "none" }}><a href="/">Phione</a></li>
          <li style={{ display: "none" }}><a href="/">Manaphy</a></li>
          <li style={{ display: "none" }}><a href="/">Darkrai</a></li>
          <li style={{ display: "none" }}><a href="/">Shaymin</a></li>
          <li style={{ display: "none" }}><a href="/">Arceus</a></li>
          <li style={{ display: "none" }}><a href="/">Victini</a></li>
          <li style={{ display: "none" }}><a href="/">Snivy</a></li>
          <li style={{ display: "none" }}><a href="/">Servine</a></li>
          <li style={{ display: "none" }}><a href="/">Serperior</a></li>
          <li style={{ display: "none" }}><a href="/">Tepig</a></li>
          <li style={{ display: "none" }}><a href="/">Pignite</a></li>
          <li style={{ display: "none" }}><a href="/">Emboar</a></li>
          <li style={{ display: "none" }}><a href="/">Oshawott</a></li>
          <li style={{ display: "none" }}><a href="/">Dewott</a></li>
          <li style={{ display: "none" }}><a href="/">Samurott</a></li>
          <li style={{ display: "none" }}><a href="/">Patrat</a></li>
          <li style={{ display: "none" }}><a href="/">Watchog</a></li>
          <li style={{ display: "none" }}><a href="/">Lillipup</a></li>
          <li style={{ display: "none" }}><a href="/">Herdier</a></li>
          <li style={{ display: "none" }}><a href="/">Stoutland</a></li>
          <li style={{ display: "none" }}><a href="/">Purrloin</a></li>
          <li style={{ display: "none" }}><a href="/">Liepard</a></li>
          <li style={{ display: "none" }}><a href="/">Pansage</a></li>
          <li style={{ display: "none" }}><a href="/">Simisage</a></li>
          <li style={{ display: "none" }}><a href="/">Pansear</a></li>
          <li style={{ display: "none" }}><a href="/">Simisear</a></li>
          <li style={{ display: "none" }}><a href="/">Panpour</a></li>
          <li style={{ display: "none" }}><a href="/">Simipour</a></li>
          <li style={{ display: "none" }}><a href="/">Munna</a></li>
          <li style={{ display: "none" }}><a href="/">Musharna</a></li>
          <li style={{ display: "none" }}><a href="/">Pidove</a></li>
          <li style={{ display: "none" }}><a href="/">Tranquill</a></li>
          <li style={{ display: "none" }}><a href="/">Unfezant</a></li>
          <li style={{ display: "none" }}><a href="/">Blitzle</a></li>
          <li style={{ display: "none" }}><a href="/">Zebstrika</a></li>
          <li style={{ display: "none" }}><a href="/">Roggenrola</a></li>
          <li style={{ display: "none" }}><a href="/">Boldore</a></li>
          <li style={{ display: "none" }}><a href="/">Gigalith</a></li>
          <li style={{ display: "none" }}><a href="/">Woobat</a></li>
          <li style={{ display: "none" }}><a href="/">Swoobat</a></li>
          <li style={{ display: "none" }}><a href="/">Drilbur</a></li>
          <li style={{ display: "none" }}><a href="/">Excadrill</a></li>
          <li style={{ display: "none" }}><a href="/">Audino</a></li>
          <li style={{ display: "none" }}><a href="/">Timburr</a></li>
          <li style={{ display: "none" }}><a href="/">Gurdurr</a></li>
          <li style={{ display: "none" }}><a href="/">Conkeldurr</a></li>
          <li style={{ display: "none" }}><a href="/">Tympole</a></li>
          <li style={{ display: "none" }}><a href="/">Palpitoad</a></li>
          <li style={{ display: "none" }}><a href="/">Seismitoad</a></li>
          <li style={{ display: "none" }}><a href="/">Throh</a></li>
          <li style={{ display: "none" }}><a href="/">Sawk</a></li>
          <li style={{ display: "none" }}><a href="/">Sewaddle</a></li>
          <li style={{ display: "none" }}><a href="/">Swadloon</a></li>
          <li style={{ display: "none" }}><a href="/">Leavanny</a></li>
          <li style={{ display: "none" }}><a href="/">Venipede</a></li>
          <li style={{ display: "none" }}><a href="/">Whirlipede</a></li>
          <li style={{ display: "none" }}><a href="/">Scolipede</a></li>
          <li style={{ display: "none" }}><a href="/">Cottonee</a></li>
          <li style={{ display: "none" }}><a href="/">Whimsicott</a></li>
          <li style={{ display: "none" }}><a href="/">Petilil</a></li>
          <li style={{ display: "none" }}><a href="/">Lilligant</a></li>
          <li style={{ display: "none" }}><a href="/">Basculin</a></li>
          <li style={{ display: "none" }}><a href="/">Sandile</a></li>
          <li style={{ display: "none" }}><a href="/">Krokorok</a></li>
          <li style={{ display: "none" }}><a href="/">Krookodile</a></li>
          <li style={{ display: "none" }}><a href="/">Darumaka</a></li>
          <li style={{ display: "none" }}><a href="/">Darmanitan</a></li>
          <li style={{ display: "none" }}><a href="/">Maractus</a></li>
          <li style={{ display: "none" }}><a href="/">Dwebble</a></li>
          <li style={{ display: "none" }}><a href="/">Crustle</a></li>
          <li style={{ display: "none" }}><a href="/">Scraggy</a></li>
          <li style={{ display: "none" }}><a href="/">Scrafty</a></li>
          <li style={{ display: "none" }}><a href="/">Sigilyph</a></li>
          <li style={{ display: "none" }}><a href="/">Yamask</a></li>
          <li style={{ display: "none" }}><a href="/">Cofagrigus</a></li>
          <li style={{ display: "none" }}><a href="/">Tirtouga</a></li>
          <li style={{ display: "none" }}><a href="/">Carracosta</a></li>
          <li style={{ display: "none" }}><a href="/">Archen</a></li>
          <li style={{ display: "none" }}><a href="/">Archeops</a></li>
          <li style={{ display: "none" }}><a href="/">Trubbish</a></li>
          <li style={{ display: "none" }}><a href="/">Garbodor</a></li>
          <li style={{ display: "none" }}><a href="/">Zorua</a></li>
          <li style={{ display: "none" }}><a href="/">Zoroark</a></li>
          <li style={{ display: "none" }}><a href="/">Minccino</a></li>
          <li style={{ display: "none" }}><a href="/">Cinccino</a></li>
          <li style={{ display: "none" }}><a href="/">Gothita</a></li>
          <li style={{ display: "none" }}><a href="/">Gothorita</a></li>
          <li style={{ display: "none" }}><a href="/">Gothitelle</a></li>
          <li style={{ display: "none" }}><a href="/">Solosis</a></li>
          <li style={{ display: "none" }}><a href="/">Duosion</a></li>
          <li style={{ display: "none" }}><a href="/">Reuniclus</a></li>
          <li style={{ display: "none" }}><a href="/">Ducklett</a></li>
          <li style={{ display: "none" }}><a href="/">Swanna</a></li>
          <li style={{ display: "none" }}><a href="/">Vanillite</a></li>
          <li style={{ display: "none" }}><a href="/">Vanillish</a></li>
          <li style={{ display: "none" }}><a href="/">Vanilluxe</a></li>
          <li style={{ display: "none" }}><a href="/">Deerling</a></li>
          <li style={{ display: "none" }}><a href="/">Sawsbuck</a></li>
          <li style={{ display: "none" }}><a href="/">Emolga</a></li>
          <li style={{ display: "none" }}><a href="/">Karrablast</a></li>
          <li style={{ display: "none" }}><a href="/">Escavalier</a></li>
          <li style={{ display: "none" }}><a href="/">Foongus</a></li>
          <li style={{ display: "none" }}><a href="/">Amoonguss</a></li>
          <li style={{ display: "none" }}><a href="/">Frillish</a></li>
          <li style={{ display: "none" }}><a href="/">Jellicent</a></li>
          <li style={{ display: "none" }}><a href="/">Alomomola</a></li>
          <li style={{ display: "none" }}><a href="/">Joltik</a></li>
          <li style={{ display: "none" }}><a href="/">Galvantula</a></li>
          <li style={{ display: "none" }}><a href="/">Ferroseed</a></li>
          <li style={{ display: "none" }}><a href="/">Ferrothorn</a></li>
          <li style={{ display: "none" }}><a href="/">Klink</a></li>
          <li style={{ display: "none" }}><a href="/">Klang</a></li>
          <li style={{ display: "none" }}><a href="/">Klinklang</a></li>
          <li style={{ display: "none" }}><a href="/">Tynamo</a></li>
          <li style={{ display: "none" }}><a href="/">Eelektrik</a></li>
          <li style={{ display: "none" }}><a href="/">Eelektross</a></li>
          <li style={{ display: "none" }}><a href="/">Elgyem</a></li>
          <li style={{ display: "none" }}><a href="/">Beheeyem</a></li>
          <li style={{ display: "none" }}><a href="/">Litwick</a></li>
          <li style={{ display: "none" }}><a href="/">Lampent</a></li>
          <li style={{ display: "none" }}><a href="/">Chandelure</a></li>
          <li style={{ display: "none" }}><a href="/">Axew</a></li>
          <li style={{ display: "none" }}><a href="/">Fraxure</a></li>
          <li style={{ display: "none" }}><a href="/">Haxorus</a></li>
          <li style={{ display: "none" }}><a href="/">Cubchoo</a></li>
          <li style={{ display: "none" }}><a href="/">Beartic</a></li>
          <li style={{ display: "none" }}><a href="/">Cryogonal</a></li>
          <li style={{ display: "none" }}><a href="/">Shelmet</a></li>
          <li style={{ display: "none" }}><a href="/">Accelgor</a></li>
          <li style={{ display: "none" }}><a href="/">Stunfisk</a></li>
          <li style={{ display: "none" }}><a href="/">Mienfoo</a></li>
          <li style={{ display: "none" }}><a href="/">Mienshao</a></li>
          <li style={{ display: "none" }}><a href="/">Druddigon</a></li>
          <li style={{ display: "none" }}><a href="/">Golett</a></li>
          <li style={{ display: "none" }}><a href="/">Golurk</a></li>
          <li style={{ display: "none" }}><a href="/">Pawniard</a></li>
          <li style={{ display: "none" }}><a href="/">Bisharp</a></li>
          <li style={{ display: "none" }}><a href="/">Bouffalant</a></li>
          <li style={{ display: "none" }}><a href="/">Rufflet</a></li>
          <li style={{ display: "none" }}><a href="/">Braviary</a></li>
          <li style={{ display: "none" }}><a href="/">Vullaby</a></li>
          <li style={{ display: "none" }}><a href="/">Mandibuzz</a></li>
          <li style={{ display: "none" }}><a href="/">Heatmor</a></li>
          <li style={{ display: "none" }}><a href="/">Durant</a></li>
          <li style={{ display: "none" }}><a href="/">Deino</a></li>
          <li style={{ display: "none" }}><a href="/">Zweilous</a></li>
          <li style={{ display: "none" }}><a href="/">Hydreigon</a></li>
          <li style={{ display: "none" }}><a href="/">Larvesta</a></li>
          <li style={{ display: "none" }}><a href="/">Volcarona</a></li>
          <li style={{ display: "none" }}><a href="/">Cobalion</a></li>
          <li style={{ display: "none" }}><a href="/">Terrakion</a></li>
          <li style={{ display: "none" }}><a href="/">Virizion</a></li>
          <li style={{ display: "none" }}><a href="/">Tornadus</a></li>
          <li style={{ display: "none" }}><a href="/">Thundurus</a></li>
          <li style={{ display: "none" }}><a href="/">Reshiram</a></li>
          <li style={{ display: "none" }}><a href="/">Zekrom</a></li>
          <li style={{ display: "none" }}><a href="/">Landorus</a></li>
          <li style={{ display: "none" }}><a href="/">Kyurem</a></li>
          <li style={{ display: "none" }}><a href="/">Keldeo</a></li>
          <li style={{ display: "none" }}><a href="/">Meloetta</a></li>
          <li style={{ display: "none" }}><a href="/">Genesect</a></li>
          <li style={{ display: "none" }}><a href="/">Chespin</a></li>
          <li style={{ display: "none" }}><a href="/">Quilladin</a></li>
          <li style={{ display: "none" }}><a href="/">Chesnaught</a></li>
          <li style={{ display: "none" }}><a href="/">Fennekin</a></li>
          <li style={{ display: "none" }}><a href="/">Braixen</a></li>
          <li style={{ display: "none" }}><a href="/">Delphox</a></li>
          <li style={{ display: "none" }}><a href="/">Froakie</a></li>
          <li style={{ display: "none" }}><a href="/">Frogadier</a></li>
          <li style={{ display: "none" }}><a href="/">Greninja</a></li>
          <li style={{ display: "none" }}><a href="/">Bunnelby</a></li>
          <li style={{ display: "none" }}><a href="/">Diggersby</a></li>
          <li style={{ display: "none" }}><a href="/">Fletchling</a></li>
          <li style={{ display: "none" }}><a href="/">Fletchinder</a></li>
          <li style={{ display: "none" }}><a href="/">Talonflame</a></li>
          <li style={{ display: "none" }}><a href="/">Scatterbug</a></li>
          <li style={{ display: "none" }}><a href="/">Spewpa</a></li>
          <li style={{ display: "none" }}><a href="/">Vivillon</a></li>
          <li style={{ display: "none" }}><a href="/">Litleo</a></li>
          <li style={{ display: "none" }}><a href="/">Pyroar</a></li>
          <li style={{ display: "none" }}><a href="/">Flabébé</a></li>
          <li style={{ display: "none" }}><a href="/">Floette</a></li>
          <li style={{ display: "none" }}><a href="/">Florges</a></li>
          <li style={{ display: "none" }}><a href="/">Skiddo</a></li>
          <li style={{ display: "none" }}><a href="/">Gogoat</a></li>
          <li style={{ display: "none" }}><a href="/">Pancham</a></li>
          <li style={{ display: "none" }}><a href="/">Pangoro</a></li>
          <li style={{ display: "none" }}><a href="/">Furfrou</a></li>
          <li style={{ display: "none" }}><a href="/">Espurr</a></li>
          <li style={{ display: "none" }}><a href="/">Meowstic</a></li>
          <li style={{ display: "none" }}><a href="/">Honedge</a></li>
          <li style={{ display: "none" }}><a href="/">Doublade</a></li>
          <li style={{ display: "none" }}><a href="/">Aegislash</a></li>
          <li style={{ display: "none" }}><a href="/">Spritzee</a></li>
          <li style={{ display: "none" }}><a href="/">Aromatisse</a></li>
          <li style={{ display: "none" }}><a href="/">Swirlix</a></li>
          <li style={{ display: "none" }}><a href="/">Slurpuff</a></li>
          <li style={{ display: "none" }}><a href="/">Inkay</a></li>
          <li style={{ display: "none" }}><a href="/">Malamar</a></li>
          <li style={{ display: "none" }}><a href="/">Binacle</a></li>
          <li style={{ display: "none" }}><a href="/">Barbaracle</a></li>
          <li style={{ display: "none" }}><a href="/">Skrelp</a></li>
          <li style={{ display: "none" }}><a href="/">Dragalge</a></li>
          <li style={{ display: "none" }}><a href="/">Clauncher</a></li>
          <li style={{ display: "none" }}><a href="/">Clawitzer</a></li>
          <li style={{ display: "none" }}><a href="/">Helioptile</a></li>
          <li style={{ display: "none" }}><a href="/">Heliolisk</a></li>
          <li style={{ display: "none" }}><a href="/">Tyrunt</a></li>
          <li style={{ display: "none" }}><a href="/">Tyrantrum</a></li>
          <li style={{ display: "none" }}><a href="/">Amaura</a></li>
          <li style={{ display: "none" }}><a href="/">Aurorus</a></li>
          <li style={{ display: "none" }}><a href="/">Sylveon</a></li>
          <li style={{ display: "none" }}><a href="/">Hawlucha</a></li>
          <li style={{ display: "none" }}><a href="/">Dedenne</a></li>
          <li style={{ display: "none" }}><a href="/">Carbink</a></li>
          <li style={{ display: "none" }}><a href="/">Goomy</a></li>
          <li style={{ display: "none" }}><a href="/">Sliggoo</a></li>
          <li style={{ display: "none" }}><a href="/">Goodra</a></li>
          <li style={{ display: "none" }}><a href="/">Klefki</a></li>
          <li style={{ display: "none" }}><a href="/">Phantump</a></li>
          <li style={{ display: "none" }}><a href="/">Trevenant</a></li>
          <li style={{ display: "none" }}><a href="/">Pumpkaboo</a></li>
          <li style={{ display: "none" }}><a href="/">Gourgeist</a></li>
          <li style={{ display: "none" }}><a href="/">Bergmite</a></li>
          <li style={{ display: "none" }}><a href="/">Avalugg</a></li>
          <li style={{ display: "none" }}><a href="/">Noibat</a></li>
          <li style={{ display: "none" }}><a href="/">Noivern</a></li>
          <li style={{ display: "none" }}><a href="/">Xerneas</a></li>
          <li style={{ display: "none" }}><a href="/">Yveltal</a></li>
          <li style={{ display: "none" }}><a href="/">Zygarde</a></li>
          <li style={{ display: "none" }}><a href="/">Diancie</a></li>
          <li style={{ display: "none" }}><a href="/">Hoopa</a></li>
          <li style={{ display: "none" }}><a href="/">Volcanion</a></li>
          <li style={{ display: "none" }}><a href="/">Rowlet</a></li>
          <li style={{ display: "none" }}><a href="/">Dartrix</a></li>
          <li style={{ display: "none" }}><a href="/">Decidueye</a></li>
          <li style={{ display: "none" }}><a href="/">Litten</a></li>
          <li style={{ display: "none" }}><a href="/">Torracat</a></li>
          <li style={{ display: "none" }}><a href="/">Incineroar</a></li>
          <li style={{ display: "none" }}><a href="/">Popplio</a></li>
          <li style={{ display: "none" }}><a href="/">Brionne</a></li>
          <li style={{ display: "none" }}><a href="/">Primarina</a></li>
          <li style={{ display: "none" }}><a href="/">Pikipek</a></li>
          <li style={{ display: "none" }}><a href="/">Trumbeak</a></li>
          <li style={{ display: "none" }}><a href="/">Toucannon</a></li>
          <li style={{ display: "none" }}><a href="/">Yungoos</a></li>
          <li style={{ display: "none" }}><a href="/">Gumshoos</a></li>
          <li style={{ display: "none" }}><a href="/">Grubbin</a></li>
          <li style={{ display: "none" }}><a href="/">Charjabug</a></li>
          <li style={{ display: "none" }}><a href="/">Vikavolt</a></li>
          <li style={{ display: "none" }}><a href="/">Crabrawler</a></li>
          <li style={{ display: "none" }}><a href="/">Crabominable</a></li>
          <li style={{ display: "none" }}><a href="/">Oricorio</a></li>
          <li style={{ display: "none" }}><a href="/">Cutiefly</a></li>
          <li style={{ display: "none" }}><a href="/">Ribombee</a></li>
          <li style={{ display: "none" }}><a href="/">Rockruff</a></li>
          <li style={{ display: "none" }}><a href="/">Lycanroc</a></li>
          <li style={{ display: "none" }}><a href="/">Wishiwashi</a></li>
          <li style={{ display: "none" }}><a href="/">Mareanie</a></li>
          <li style={{ display: "none" }}><a href="/">Toxapex</a></li>
          <li style={{ display: "none" }}><a href="/">Mudbray</a></li>
          <li style={{ display: "none" }}><a href="/">Mudsdale</a></li>
          <li style={{ display: "none" }}><a href="/">Dewpider</a></li>
          <li style={{ display: "none" }}><a href="/">Araquanid</a></li>
          <li style={{ display: "none" }}><a href="/">Fomantis</a></li>
          <li style={{ display: "none" }}><a href="/">Lurantis</a></li>
          <li style={{ display: "none" }}><a href="/">Morelull</a></li>
          <li style={{ display: "none" }}><a href="/">Shiinotic</a></li>
          <li style={{ display: "none" }}><a href="/">Salandit</a></li>
          <li style={{ display: "none" }}><a href="/">Salazzle</a></li>
          <li style={{ display: "none" }}><a href="/">Stufful</a></li>
          <li style={{ display: "none" }}><a href="/">Bewear</a></li>
          <li style={{ display: "none" }}><a href="/">Bounsweet</a></li>
          <li style={{ display: "none" }}><a href="/">Steenee</a></li>
          <li style={{ display: "none" }}><a href="/">Tsareena</a></li>
          <li style={{ display: "none" }}><a href="/">Comfey</a></li>
          <li style={{ display: "none" }}><a href="/">Oranguru</a></li>
          <li style={{ display: "none" }}><a href="/">Passimian</a></li>
          <li style={{ display: "none" }}><a href="/">Wimpod</a></li>
          <li style={{ display: "none" }}><a href="/">Golisopod</a></li>
          <li style={{ display: "none" }}><a href="/">Sandygast</a></li>
          <li style={{ display: "none" }}><a href="/">Palossand</a></li>
          <li style={{ display: "none" }}><a href="/">Pyukumuku</a></li>
          <li style={{ display: "none" }}><a href="/">Type: Null</a></li>
          <li style={{ display: "none" }}><a href="/">Silvally</a></li>
          <li style={{ display: "none" }}><a href="/">Minior</a></li>
          <li style={{ display: "none" }}><a href="/">Komala</a></li>
          <li style={{ display: "none" }}><a href="/">Turtonator</a></li>
          <li style={{ display: "none" }}><a href="/">Togedemaru</a></li>
          <li style={{ display: "none" }}><a href="/">Mimikyu</a></li>
          <li style={{ display: "none" }}><a href="/">Bruxish</a></li>
          <li style={{ display: "none" }}><a href="/">Drampa</a></li>
          <li style={{ display: "none" }}><a href="/">Dhelmise</a></li>
          <li style={{ display: "none" }}><a href="/">Jangmo-o</a></li>
          <li style={{ display: "none" }}><a href="/">Hakamo-o</a></li>
          <li style={{ display: "none" }}><a href="/">Kommo-o</a></li>
          <li style={{ display: "none" }}><a href="/">Tapu Koko</a></li>
          <li style={{ display: "none" }}><a href="/">Tapu Lele</a></li>
          <li style={{ display: "none" }}><a href="/">Tapu Bulu</a></li>
          <li style={{ display: "none" }}><a href="/">Tapu Fini</a></li>
          <li style={{ display: "none" }}><a href="/">Cosmog</a></li>
          <li style={{ display: "none" }}><a href="/">Cosmoem</a></li>
          <li style={{ display: "none" }}><a href="/">Solgaleo</a></li>
          <li style={{ display: "none" }}><a href="/">Lunala</a></li>
          <li style={{ display: "none" }}><a href="/">Nihilego</a></li>
          <li style={{ display: "none" }}><a href="/">Buzzwole</a></li>
          <li style={{ display: "none" }}><a href="/">Pheromosa</a></li>
          <li style={{ display: "none" }}><a href="/">Xurkitree</a></li>
          <li style={{ display: "none" }}><a href="/">Celesteela</a></li>
          <li style={{ display: "none" }}><a href="/">Kartana</a></li>
          <li style={{ display: "none" }}><a href="/">Guzzlord</a></li>
          <li style={{ display: "none" }}><a href="/">Necrozma</a></li>
          <li style={{ display: "none" }}><a href="/">Magearna</a></li>
          <li style={{ display: "none" }}><a href="/">Marshadow</a></li>
          <li style={{ display: "none" }}><a href="/">Poipole</a></li>
          <li style={{ display: "none" }}><a href="/">Naganadel</a></li>
          <li style={{ display: "none" }}><a href="/">Stakataka</a></li>
          <li style={{ display: "none" }}><a href="/">Blacephalon</a></li>
          <li style={{ display: "none" }}><a href="/">Zeraora</a></li>
          <li style={{ display: "none" }}><a href="/">Meltan</a></li>
          <li style={{ display: "none" }}><a href="/">Melmetal</a></li>
          <li style={{ display: "none" }}><a href="/">Grookey</a></li>
          <li style={{ display: "none" }}><a href="/">Thwackey</a></li>
          <li style={{ display: "none" }}><a href="/">Rillaboom</a></li>
          <li style={{ display: "none" }}><a href="/">Scorbunny</a></li>
          <li style={{ display: "none" }}><a href="/">Raboot</a></li>
          <li style={{ display: "none" }}><a href="/">Cinderace</a></li>
          <li style={{ display: "none" }}><a href="/">Sobble</a></li>
          <li style={{ display: "none" }}><a href="/">Drizzile</a></li>
          <li style={{ display: "none" }}><a href="/">Inteleon</a></li>
          <li style={{ display: "none" }}><a href="/">Skwovet</a></li>
          <li style={{ display: "none" }}><a href="/">Greedent</a></li>
          <li style={{ display: "none" }}><a href="/">Rookidee</a></li>
          <li style={{ display: "none" }}><a href="/">Corvisquire</a></li>
          <li style={{ display: "none" }}><a href="/">Corviknight</a></li>
          <li style={{ display: "none" }}><a href="/">Blipbug</a></li>
          <li style={{ display: "none" }}><a href="/">Dottler</a></li>
          <li style={{ display: "none" }}><a href="/">Orbeetle</a></li>
          <li style={{ display: "none" }}><a href="/">Nickit</a></li>
          <li style={{ display: "none" }}><a href="/">Thievul</a></li>
          <li style={{ display: "none" }}><a href="/">Gossifleur</a></li>
          <li style={{ display: "none" }}><a href="/">Eldegoss</a></li>
          <li style={{ display: "none" }}><a href="/">Wooloo</a></li>
          <li style={{ display: "none" }}><a href="/">Dubwool</a></li>
          <li style={{ display: "none" }}><a href="/">Chewtle</a></li>
          <li style={{ display: "none" }}><a href="/">Drednaw</a></li>
          <li style={{ display: "none" }}><a href="/">Yamper</a></li>
          <li style={{ display: "none" }}><a href="/">Boltund</a></li>
          <li style={{ display: "none" }}><a href="/">Rolycoly</a></li>
          <li style={{ display: "none" }}><a href="/">Carkol</a></li>
          <li style={{ display: "none" }}><a href="/">Coalossal</a></li>
          <li style={{ display: "none" }}><a href="/">Applin</a></li>
          <li style={{ display: "none" }}><a href="/">Flapple</a></li>
          <li style={{ display: "none" }}><a href="/">Appletun</a></li>
          <li style={{ display: "none" }}><a href="/">Silicobra</a></li>
          <li style={{ display: "none" }}><a href="/">Sandaconda</a></li>
          <li style={{ display: "none" }}><a href="/">Cramorant</a></li>
          <li style={{ display: "none" }}><a href="/">Arrokuda</a></li>
          <li style={{ display: "none" }}><a href="/">Barraskewda</a></li>
          <li style={{ display: "none" }}><a href="/">Toxel</a></li>
          <li style={{ display: "none" }}><a href="/">Toxtricity</a></li>
          <li style={{ display: "none" }}><a href="/">Sizzlipede</a></li>
          <li style={{ display: "none" }}><a href="/">Centiskorch</a></li>
          <li style={{ display: "none" }}><a href="/">Clobbopus</a></li>
          <li style={{ display: "none" }}><a href="/">Grapploct</a></li>
          <li style={{ display: "none" }}><a href="/">Sinistea</a></li>
          <li style={{ display: "none" }}><a href="/">Polteageist</a></li>
          <li style={{ display: "none" }}><a href="/">Hatenna</a></li>
          <li style={{ display: "none" }}><a href="/">Hattrem</a></li>
          <li style={{ display: "none" }}><a href="/">Hatterene</a></li>
          <li style={{ display: "none" }}><a href="/">Impidimp</a></li>
          <li style={{ display: "none" }}><a href="/">Morgrem</a></li>
          <li style={{ display: "none" }}><a href="/">Grimmsnarl</a></li>
          <li style={{ display: "none" }}><a href="/">Obstagoon</a></li>
          <li style={{ display: "none" }}><a href="/">Perrserker</a></li>
          <li style={{ display: "none" }}><a href="/">Cursola</a></li>
          <li style={{ display: "none" }}><a href="/">Sirfetch'd</a></li>
          <li style={{ display: "none" }}><a href="/">Mr. Rime</a></li>
          <li style={{ display: "none" }}><a href="/">Runerigus</a></li>
          <li style={{ display: "none" }}><a href="/">Milcery</a></li>
          <li style={{ display: "none" }}><a href="/">Alcremie</a></li>
          <li style={{ display: "none" }}><a href="/">Falinks</a></li>
          <li style={{ display: "none" }}><a href="/">Pincurchin</a></li>
          <li style={{ display: "none" }}><a href="/">Snom</a></li>
          <li style={{ display: "none" }}><a href="/">Frosmoth</a></li>
          <li style={{ display: "none" }}><a href="/">Stonjourner</a></li>
          <li style={{ display: "none" }}><a href="/">Eiscue</a></li>
          <li style={{ display: "none" }}><a href="/">Indeedee</a></li>
          <li style={{ display: "none" }}><a href="/">Morpeko</a></li>
          <li style={{ display: "none" }}><a href="/">Cufant</a></li>
          <li style={{ display: "none" }}><a href="/">Copperajah</a></li>
          <li style={{ display: "none" }}><a href="/">Dracozolt</a></li>
          <li style={{ display: "none" }}><a href="/">Arctozolt</a></li>
          <li style={{ display: "none" }}><a href="/">Dracovish</a></li>
          <li style={{ display: "none" }}><a href="/">Arctovish</a></li>
          <li style={{ display: "none" }}><a href="/">Duraludon</a></li>
          <li style={{ display: "none" }}><a href="/">Dreepy</a></li>
          <li style={{ display: "none" }}><a href="/">Drakloak</a></li>
          <li style={{ display: "none" }}><a href="/">Dragapult</a></li>
          <li style={{ display: "none" }}><a href="/">Zacian</a></li>
          <li style={{ display: "none" }}><a href="/">Zamazenta</a></li>
          <li style={{ display: "none" }}><a href="/">Eternatus</a></li>
          <li style={{ display: "none" }}><a href="/">Kubfu</a></li>
          <li style={{ display: "none" }}><a href="/">Urshifu</a></li>
          <li style={{ display: "none" }}><a href="/">Zarude</a></li>
          <li style={{ display: "none" }}><a href="/">Regieleki</a></li>
          <li style={{ display: "none" }}><a href="/">Regidrago</a></li>
          <li style={{ display: "none" }}><a href="/">Glastrier</a></li>
          <li style={{ display: "none" }}><a href="/">Spectrier</a></li>
          <li style={{ display: "none" }}><a href="/">Calyrex</a></li>
          <li style={{ display: "none" }}><a href="/">Wyrdeer</a></li>
          <li style={{ display: "none" }}><a href="/">Kleavor</a></li>
          <li style={{ display: "none" }}><a href="/">Ursaluna</a></li>
          <li style={{ display: "none" }}><a href="/">Basculegion</a></li>
          <li style={{ display: "none" }}><a href="/">Sneasler</a></li>
          <li style={{ display: "none" }}><a href="/">Overqwil</a></li>
          <li style={{ display: "none" }}><a href="/">Enamorus</a></li>
          <li style={{ display: "none" }}><a href="/">Sprigatito</a></li>
          <li style={{ display: "none" }}><a href="/">Floragato</a></li>
          <li style={{ display: "none" }}><a href="/">Meowscarada</a></li>
          <li style={{ display: "none" }}><a href="/">Fuecoco</a></li>
          <li style={{ display: "none" }}><a href="/">Crocalor</a></li>
          <li style={{ display: "none" }}><a href="/">Skeledirge</a></li>
          <li style={{ display: "none" }}><a href="/">Quaxly</a></li>
          <li style={{ display: "none" }}><a href="/">Quaxwell</a></li>
          <li style={{ display: "none" }}><a href="/">Quaquaval</a></li>
          <li style={{ display: "none" }}><a href="/">Lechonk</a></li>
          <li style={{ display: "none" }}><a href="/">Oinkologne</a></li>
          <li style={{ display: "none" }}><a href="/">Tarountula</a></li>
          <li style={{ display: "none" }}><a href="/">Spidops</a></li>
          <li style={{ display: "none" }}><a href="/">Nymble</a></li>
          <li style={{ display: "none" }}><a href="/">Lokix</a></li>
          <li style={{ display: "none" }}><a href="/">Pawmi</a></li>
          <li style={{ display: "none" }}><a href="/">Pawmo</a></li>
          <li style={{ display: "none" }}><a href="/">Pawmot</a></li>
          <li style={{ display: "none" }}><a href="/">Tandemaus</a></li>
          <li style={{ display: "none" }}><a href="/">Maushold</a></li>
          <li style={{ display: "none" }}><a href="/">Fidough</a></li>
          <li style={{ display: "none" }}><a href="/">Dachsbun</a></li>
          <li style={{ display: "none" }}><a href="/">Smoliv</a></li>
          <li style={{ display: "none" }}><a href="/">Dolliv</a></li>
          <li style={{ display: "none" }}><a href="/">Arboliva</a></li>
          <li style={{ display: "none" }}><a href="/">Squawkabilly</a></li>
          <li style={{ display: "none" }}><a href="/">Nacli</a></li>
          <li style={{ display: "none" }}><a href="/">Naclstack</a></li>
          <li style={{ display: "none" }}><a href="/">Garganacl</a></li>
          <li style={{ display: "none" }}><a href="/">Charcadet</a></li>
          <li style={{ display: "none" }}><a href="/">Armarouge</a></li>
          <li style={{ display: "none" }}><a href="/">Ceruledge</a></li>
          <li style={{ display: "none" }}><a href="/">Tadbulb</a></li>
          <li style={{ display: "none" }}><a href="/">Bellibolt</a></li>
          <li style={{ display: "none" }}><a href="/">Wattrel</a></li>
          <li style={{ display: "none" }}><a href="/">Kilowattrel</a></li>
          <li style={{ display: "none" }}><a href="/">Maschiff</a></li>
          <li style={{ display: "none" }}><a href="/">Mabosstiff</a></li>
          <li style={{ display: "none" }}><a href="/">Shroodle</a></li>
          <li style={{ display: "none" }}><a href="/">Grafaiai</a></li>
          <li style={{ display: "none" }}><a href="/">Bramblin</a></li>
          <li style={{ display: "none" }}><a href="/">Brambleghast</a></li>
          <li style={{ display: "none" }}><a href="/">Toedscool</a></li>
          <li style={{ display: "none" }}><a href="/">Toedscruel</a></li>
          <li style={{ display: "none" }}><a href="/">Klawf</a></li>
          <li style={{ display: "none" }}><a href="/">Capsakid</a></li>
          <li style={{ display: "none" }}><a href="/">Scovillain</a></li>
          <li style={{ display: "none" }}><a href="/">Rellor</a></li>
          <li style={{ display: "none" }}><a href="/">Rabsca</a></li>
          <li style={{ display: "none" }}><a href="/">Flittle</a></li>
          <li style={{ display: "none" }}><a href="/">Espathra</a></li>
          <li style={{ display: "none" }}><a href="/">Tinkatink</a></li>
          <li style={{ display: "none" }}><a href="/">Tinkatuff</a></li>
          <li style={{ display: "none" }}><a href="/">Tinkaton</a></li>
          <li style={{ display: "none" }}><a href="/">Wiglett</a></li>
          <li style={{ display: "none" }}><a href="/">Wugtrio</a></li>
          <li style={{ display: "none" }}><a href="/">Bombirdier</a></li>
          <li style={{ display: "none" }}><a href="/">Finizen</a></li>
          <li style={{ display: "none" }}><a href="/">Palafin</a></li>
          <li style={{ display: "none" }}><a href="/">Varoom</a></li>
          <li style={{ display: "none" }}><a href="/">Revavroom</a></li>
          <li style={{ display: "none" }}><a href="/">Cyclizar</a></li>
          <li style={{ display: "none" }}><a href="/">Orthworm</a></li>
          <li style={{ display: "none" }}><a href="/">Glimmet</a></li>
          <li style={{ display: "none" }}><a href="/">Glimmora</a></li>
          <li style={{ display: "none" }}><a href="/">Greavard</a></li>
          <li style={{ display: "none" }}><a href="/">Houndstone</a></li>
          <li style={{ display: "none" }}><a href="/">Flamigo</a></li>
          <li style={{ display: "none" }}><a href="/">Cetoddle</a></li>
          <li style={{ display: "none" }}><a href="/">Cetitan</a></li>
          <li style={{ display: "none" }}><a href="/">Veluza</a></li>
          <li style={{ display: "none" }}><a href="/">Dondozo</a></li>
          <li style={{ display: "none" }}><a href="/">Tatsugiri</a></li>
          <li style={{ display: "none" }}><a href="/">Annihilape</a></li>
          <li style={{ display: "none" }}><a href="/">Clodsire</a></li>
          <li style={{ display: "none" }}><a href="/">Farigiraf</a></li>
          <li style={{ display: "none" }}><a href="/">Dudunsparce</a></li>
          <li style={{ display: "none" }}><a href="/">Kingambit</a></li>
          <li style={{ display: "none" }}><a href="/">Great Tusk</a></li>
          <li style={{ display: "none" }}><a href="/">Scream Tail</a></li>
          <li style={{ display: "none" }}><a href="/">Brute Bonnet</a></li>
          <li style={{ display: "none" }}><a href="/">Flutter Mane</a></li>
          <li style={{ display: "none" }}><a href="/">Slither Wing</a></li>
          <li style={{ display: "none" }}><a href="/">Sandy Shocks</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Treads</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Bundle</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Hands</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Jugulis</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Moth</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Thorns</a></li>
          <li style={{ display: "none" }}><a href="/">Frigibax</a></li>
          <li style={{ display: "none" }}><a href="/">Arctibax</a></li>
          <li style={{ display: "none" }}><a href="/">Baxcalibur</a></li>
          <li style={{ display: "none" }}><a href="/">Gimmighoul</a></li>
          <li style={{ display: "none" }}><a href="/">Gholdengo</a></li>
          <li style={{ display: "none" }}><a href="/">Wo-Chien</a></li>
          <li style={{ display: "none" }}><a href="/">Chien-Pao</a></li>
          <li style={{ display: "none" }}><a href="/">Ting-Lu</a></li>
          <li style={{ display: "none" }}><a href="/">Chi-Yu</a></li>
          <li style={{ display: "none" }}><a href="/">Roaring Moon</a></li>
          <li style={{ display: "none" }}><a href="/">Iron Valiant</a></li>
          <li style={{ display: "none" }}><a href="/">Koraidon</a></li>
          <li style={{ display: "none" }}><a href="/">Miraidon</a></li>
        </ul>
      </div>
    </>
  )
  return data
}

const searchMons = (e) => {
  console.log("hi" + e);

  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  ul = document.getElementById("myUL");
  li = ul.getElementsByTagName("li");
  if(input.value === '') {
    for (i = 0; i < li.length; i++) {
      if(i < 9) {
        li[i].style.display = "";
      } else {
        li[i].style.display = "none";
      }
    }
  } else {
    for (i = 0; i < li.length; i++) {
      a = li[i].getElementsByTagName("a")[0];
      txtValue = a.textContent || a.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "";
      } else {
        li[i].style.display = "none";
      }
    }
  }
}

export { ChoosePokemonForm }